Travel/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :reviews do
      resources :likes
      resources :dislikes
    end
  end
  
  resources :users

  get '/places/:place_id/set_favorite/:id', to: 'users#favorite', as: 'set_favorite'
  
  get '/static_pages/home/find', to: 'places#find', as: 'find_place'

  get '/places/my_reviews/:id', to: 'users#reviews', as: 'my_reviews'

  get '/users/:id/ban', to: 'users#ban', as: 'ban_user'

  get '/users/:id/unban', to: 'users#unban', as: 'unban_user'

  get '/users/:id/promote', to: 'users#promote', as: 'promote_user'
  
  get '/users/:id/demote', to: 'users#demote', as: 'demote_user'

  get '/places/:id/find_route', to: 'places#find_route',  as: 'find_route'

  get '/places/:id/display_route', to: 'places#display_route',  as: 'display_route'
  
  get 'static_pages/home'
  
  get 'static_pages/help'
  
  root :to  => redirect('/static_pages/home')

end

Travel/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    # default: render ’home’ template
  end

  def help
    # default: render ’help’ template
  end
  
end

Travel/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Travel/app/views/static_pages/help.html.erb
<html>
<link href="../../assets/stylesheets/login.css" rel="stylesheet">
<p></p>
<title>Travelling</title>
<h1></h1>
<div calss="top">
    <h1>Hai delle domande o bisogno di supporto ?</h1>
    <p>Se necessiti di aiuto o semplicemente di informazioni puoi contattarci a questa mail: travelhelp@gmail.com</p>
    <h1> Credi di essere in grado di far parte del team?</h1>
    <p>Puoi contattarci per discutere del tuo inserimento nel nostro team a questa mail: jointravel@gmail.com . 
        Ti preghiamo di specificare le tue conoscenze all'interno della mail il più dettagliatamente possibile, ricordati di indicare inoltre le tue eventuali referenze!
    </p>
    <h1>Info</h1>
    <p>
        Questa piattaforma è stata creata per permettere a chi ama viaggiare di trovare e apprezzare luoghi sconosciuti che spesso negli itinerari di viaggio
        standard non vengono inclusi.
        Infatti grazie al vostro aiuto stiamo cercando di creare una community sempre più grande! perchè?
        perchè voi stessi potete far scoprire questi posti a gli altri utenti, navigando sul sito sarete in grado di inserire, modificare e recensire dei posti scegliendo addirittura 
        il vostro preferito.
        Se possedete quindi un'attività o semplicemente conoscete un posto che secondo voi bisognerebbe assolutamente visitare, potrete inserirlo e descriverlo su questa piattaforma.
        Avrete inoltre la possibilità di modificare il vostro profilo e inserire un'immagine per farvi conoscere.

    </p>
</div>
</html>

Travel/app/views/static_pages/home.html.erb
<link rel="stylesheet" href="../../assets/static_pages/Homepage.css">

<% if ( !current_user.nil? && current_user.is?(:banned)) %>
    <h1> You was Banned, you can't acces the site </h1>
<%else%>

    <h1 style="text-align:center"><strong><font color="white">Travel with Us!!</font></strong></h1><br>
    <div id="search">
        <%= form_tag find_place_path, method: :get do %>
            <%= text_field_tag 'name',nil, placeholder: 'Find a place', size:37, :class=>"form-control", id:"ser" %>
            <br/>
            <%= submit_tag 'Search', id:"searchsub", :class=>"btn btn-danger btn-block action" %>
        <%end%>
    </div>
    <br/>
        <div class="box">
            <div align="center">
            
                <h1>Top Places</h1><br/>
                <% Place.order(:avarage => 'desc').limit(4).each do |place| %>
                    <div class="boxphoto">
                        <%= icon_for place%>
                        <h3><%= place.name %></h3>
                        <p><%= place.city %></p>
                        <p><button type="button" class="btn btn-danger" style = "padding: 8px 60px;" onclick="window.location.href='/places/<%= place.id %>'"><a></a><h5>Visita!</h5></button></p>
                    </div>
                <%end%>
            </div>
        </div>

        <div class="boxp">
            <div class="title">
                <h1>Top Users</h1>
            </div>
            <% User.order(:num_dislikes,num_likes: :desc).limit(4).each do |user| %>
                    <div class="boxphoto">
                        <%= gravatar_for user%>
                        <h3><%= user.name %></h3>
                        <p><button type="button" class="btn btn-danger" style = "padding: 8px 60px;" onclick="window.location.href='/users/<%= user.id %>'"><a></a><h5>Visita!</h5></button></p>
                    </div>
                <%end%>

        </div>
<%end%>