Travel/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :reviews do
      resources :likes
      resources :dislikes
    end
  end
  
  resources :users

  get '/places/:place_id/set_favorite/:id', to: 'users#favorite', as: 'set_favorite'
  
  get '/static_pages/home/find', to: 'places#find', as: 'find_place'

  get '/places/my_reviews/:id', to: 'users#reviews', as: 'my_reviews'

  get '/users/:id/ban', to: 'users#ban', as: 'ban_user'

  get '/users/:id/unban', to: 'users#unban', as: 'unban_user'

  get '/users/:id/promote', to: 'users#promote', as: 'promote_user'
  
  get '/users/:id/demote', to: 'users#demote', as: 'demote_user'

  get '/places/:id/find_route', to: 'places#find_route',  as: 'find_route'

  get '/places/:id/display_route', to: 'places#display_route',  as: 'display_route'
  
  get 'static_pages/home'
  
  get 'static_pages/help'
  
  root :to  => redirect('/static_pages/home')

end

Travel/app/models/place.rb
class Place < ActiveRecord::Base

    before_create :set_default_average
    has_many :reviews
    belongs_to :user, optional: true
    #attr_accessible :name, :street, :address, :city, :telephone_number, :opening_time, :closing_time, :description, :notices
    validates :name, :presence => true
    validates :street, :presence => true
    validates :address, :presence => true
    validates :city, :presence => true

    private
    
    def set_default_average
        self.average = 0
    end

end

Travel/app/controllers/places_controller.rb
class PlacesController < ApplicationController

    before_action :authenticate_user!
    
    def index
        if current_user.is? :admin
            @places = Place.all
        else
            flash[:warning] = "You are not authorized to read all places"
            redirect_to root_path
        end
    end
    
    def show
        begin
            id = params[:id] # retrieve place ID from URI route
            @place = Place.find(id)
            authorize! :read, @place, :message => "BEWARE: You are not authorized to read a place."
        rescue ActiveRecord::RecordNotFound 
            redirect_to :controller => "places", :action => "index"
            flash[:warning] = "There is no place with that index"
            return
        end
        # will render app/views/places/show.html.haml by default
    end

    def new
        # default: render ’new’ template
    end

    def create
        @owner = current_user
        @place = @owner.property.build(params[:place].permit(:name, :street, :address, :city, :telephone_number, :opening_time, :closing_time, :description, :notices, :icon))
        authorize! :create, @place, :message => "BEWARE: You are not authorized to create a new place."
        @place.save!
        if !(@owner.is?(:owner))
            @owner.roles = @owner.roles << :owner
        end
        @owner.save!
        respond_to do |client_wants|
            client_wants.html {
                flash[:notice] = "#{@place.name} was successfully created."
                redirect_to root_path
            }
            client_wants.xml { render :xml => @place.to_xml }
        end
    end

    def edit
        @place = Place.find params[:id]
        authorize! :update, @place, :message => "BEWARE: You are not authorized to edit a place."
        if current_user != @place.user
            flash[:warning] = "You are not authorized to edit this place"
            redirect_to place_path(@place)
        end
    end

    def update
        @place = Place.find params[:id]
        authorize! :update, @place, :message => "BEWARE: You are not authorized to update a place."
        if current_user != @place.user
            flash[:warning] = "You are not authorized to update this place"
            redirect_to place_path(@place)
        end
        @place.update_attributes!(params[:place].permit(:name, :street, :address, :city, :telephone_number, :opening_time, :closing_time, :description, :notices, :icon))
        respond_to do |client_wants|
            client_wants.html {
                flash[:notice] = "#{@place.name} was successfully updated."
                redirect_to place_path(@place)
            }
            client_wants.xml { render :xml => @place.to_xml }
        end
    end

    def destroy
        @place = Place.find(params[:id])
        authorize! :destroy, @place, :message => "BEWARE: You are not authorized to delete a place."
        if current_user != @place.user && !current_user.is?(:moderator) && !current_user.is?(:admin)
            flash[:warning] = "You are not authorized to delete this place"
            redirect_to place_path(@place)
        end
        @place.destroy
        flash[:notice] = "Place #{@place.name} deleted."
        redirect_to root_path
    end
    
    def find
        @places = Place.where(name: params[:name])
        # authorize! :read, @places, :message => "BEWARE: You are not authorized to find a place."
    end

    def find_route
        # default: render ’find_route’ template
    end
    
    def display_route
        @facilities = params[:Facilities]
        @departureAddress = params[:From]
        @place = Place.find(params[:id])
        @desiredDestination = @place.street + ', ' + @place.address.to_s + ', ' + @place.city
        # default: render ’display_route’ template
    end

end

Travel/app/helpers/places_helper.rb
module PlacesHelper
  
  # Returns the Gravatar for the given place.
  def icon_for(place)
      
    if place.icon == nil || place.icon == ""
        icon = "#{root_url}assets/place.png"
    else
        icon = place.icon
    end
    image_tag(icon, alt: place.icon, class: "gravatar",  size: "180x180")
  end
  
end

Travel/app/views/places/_place_form.html.erb
<div>
    <div class="col-md-5 box">
        <div>
            <div class="field">
                <div><label><h2>Name<h2></label></div>
                <%= text_field :place, :name, required: true, autocomplete: "name", :class => "form-control", placeholder: "Name" %>
                <br/>
                <div><label><h2>Street<h2></label></div>
                <%= text_field :place, :street, required: true, autocomplete: "street", :class => "form-control", placeholder: "Street" %>
                <br/>
                <div><label><h2>Adress<h2></label></div>
                <%= number_field :place, :address, required: true, autocomplete: "address",min: 1, :class => "form-control", placeholder: "Address" %>
                <br/>
                <div><label><h2>City<h2></label></div>
                <%= text_field :place, :city, required: true, autocomplete: "city", :class => "form-control", placeholder: "City" %>
                <br/>
                <div><label><h2>Telephone<h2></label></div>
                <%= telephone_field :place, :telephone_number, autocomplete: "adress",min: 1, max: 9999999999, :class => "form-control", placeholder: "Telephone" %>
                <br/>
            </div>
                <label><h2>Opening Time<h2></label>
                <div><%= time_field :place, :opening_time, autocomplete: "opening_time", :class => "form-control", placeholder: "Opening Time"%></div>
                <br/>
                <label><h2>Closing Time<h2></label>
                <%= time_field :place, :closing_time, autocomplete: "closing_time", :class => "form-control", placeholder: "Closing Time" %>
                <br/>
        </div>
    </div>
    <div class="col-md-2"></div>
    
    <div class="col-md-4">
        <div class="field">
            <br/><br/><br/><br/>
            <div><label><h2>Description<h2></label></div>
            <%= text_area :place, :description, autocomplete: "description", :class => "form-control", placeholder: "Description",cols: 20, rows: 7 %>
            <br/>
            <div><label><h2>Notices<h2></label></div>
            <%= text_area :place, :notices, autocomplete: "notices", :class => "form-control", placeholder: "Notices",cols: 20, rows: 7 %>
            <br/>
            <label><h2>Image Place<h2></label>
            <%= text_field :place, :icon, autocomplete: "icon", :class => "form-control", placeholder: "Image of the place" %>
            <br/>

Travel/app/views/places/display_route.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../../assets/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="../../assets/stylesheets/places/display.css" rel="stylesheet">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
</head>



<div class="logreg-forms">
    <h1 style="text-align:center"><strong>The Map<strong></h1>
    <div id="mapContainer"> </div>

</div>

<script type="text/javascript">
    if (document.readyState=='complete'){
        location.reload();
    }

    document.addEventListener('DOMContentLoaded', function(){
        var facilities = '<%= @facilities %>'
        var departureAddress = '<%= @departureAddress %>'
        var desiredDestination = '<%= @desiredDestination %>'
        // Instantiate a map and platform object:
        var platform = new H.service.Platform({
            'app_id': 'iWmGo2odqif40vyPJakz',
            'app_code': 'yjAmvBevJLWDokn2otE6Gg'
        });

        // Create the parameters for the geocoding request:
        var geocodingParams = {
            searchText: departureAddress
        };

        // Define a callback function to process the geocoding response:
        var onResultDeparture = function(result) {
            var location = result.Response.View[0].Result[0], position0;
            position0 = {
                lat: location.Location.DisplayPosition.Latitude,
                lng: location.Location.DisplayPosition.Longitude
            };
            
            // Create the parameters for the geocoding request:
            geocodingParams = {
                searchText: desiredDestination
            };

            // Define a callback function to process the geocoding response:
            var onResult = function(result) {
                var location = result.Response.View[0].Result[0], position1;
                position1 = {
                    lat: location.Location.DisplayPosition.Latitude,
                    lng: location.Location.DisplayPosition.Longitude
                }
                // Retrieve the target element for the map:
                var targetElement = document.getElementById('mapContainer');

                // Get the default map types from the platform object:
                var defaultLayers = platform.createDefaultLayers();

                // Instantiate the map:
                var map = new H.Map(
                document.getElementById('mapContainer'),
                defaultLayers.normal.map,
                {
                zoom: 10,
                center: { lat: 52.51, lng: 13.4 }
                });

                // Create the parameters for the routing request:
                var mode = facilities == 'Car' ? 'car' : 'publicTransport';
                var routingParameters = {
                // The routing mode:
                    'mode': 'fastest;' + mode, 
                    // The start point of the route:
                    'waypoint0': 'geo!' + position0.lat + ',' + position0.lng,
                    // The end point of the route:
                    'waypoint1': 'geo!' + position1.lat + ',' + position1.lng,
                    // To retrieve the shape of the route we choose the route
                    // representation mode 'display'
                    'representation': 'display'
                };

                // Define a callback function to process the routing response:
                var onResultFinal = function(result) {
                    var route,
                        routeShape,
                        startPoint,
                        endPoint,
                        linestring;
                    if(result.response.route) {
                    // Pick the first route from the response:
                    route = result.response.route[0];
                    // Pick the route's shape:
                    routeShape = route.shape;

                    // Create a linestring to use as a point source for the route line
                    linestring = new H.geo.LineString();

                    // Push all the points in the shape into the linestring:
                    routeShape.forEach(function(point) {
                        var parts = point.split(',');
                        linestring.pushLatLngAlt(parts[0], parts[1]);
                    });

                    // Retrieve the mapped positions of the requested waypoints:
                    startPoint = route.waypoint[0].mappedPosition;
                    endPoint = route.waypoint[1].mappedPosition;

                    // Create a polyline to display the route
                    routeLine = new H.map.Polyline(linestring, {
                        style: { lineWidth: 10 },
                        arrows: { fillColor: 'white', frequency: 2, width: 0.8, length: 0.7 }
                    });
                    // Create a marker for the start point:
                    var startMarker = new H.map.Marker({
                        lat: startPoint.latitude,
                        lng: startPoint.longitude
                    });

                    // Create a marker for the end point:
                    var endMarker = new H.map.Marker({
                        lat: endPoint.latitude,
                        lng: endPoint.longitude
                    });

                    // Add the route polyline and the two markers to the map:
                    map.addObjects([routeLine, startMarker, endMarker]);

                    // Set the map's viewport to make the whole route visible:
                    map.setViewBounds(routeLine.getBounds());
                    }
                };

                // Get an instance of the routing service:
                var router = platform.getRoutingService();

                // Call calculateRoute() with the routing parameters,
                // the callback and an error callback function (called if a
                // communication error occurs):
                router.calculateRoute(routingParameters, onResultFinal,
                function(error) {
                    alert(error.message);
                });


            };

            // Call the geocode method with the geocoding parameters,
            // the callback and an error callback function (called if a
            // communication error occurs):
            geocoder.geocode(geocodingParams, onResult, function(e) {
                alert(e);
            });

        };

        // Get an instance of the geocoding service:
        var geocoder = platform.getGeocodingService();

        // Call the geocode method with the geocoding parameters,
        // the callback and an error callback function (called if a
        // communication error occurs):
        geocoder.geocode(geocodingParams, onResultDeparture, function(e) {
            alert(e);
        });
    });
            
</script>

Travel/app/views/places/edit.html.haml
%h2 Edit Existing Place
 
= form_tag place_path(@place), :method => :put do
    = render :partial => 'place_form'
    = submit_tag 'Save Changes'
    

= link_to 'Cancel', places_path

Travel/app/views/places/find.html.erb
<% if @places.empty? %>
    <h1>There aren't places with that name</h1>
<%else%>

    <div class="container">
    <div class="row">
        <div class="col-md-11 scroll">
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th scope="col"><h1>Places Found</h1></th>
            </tr>
            </thead>
        </table>
<font size="2">
    <table style="width:100%">
    <thead>
        <tr>
        <th>Index</th>
        <th>Place Name</th>
        <th>Street</th>
        <th>Address</th>
        <th>City</th>
        <th>Telephone Number</th>
        <th>Opening Time</th>
        <th>Closing Time</th>
        <th>Description</th>
        <th>Notices</th>
        <th>Average</th>
        <th>More About</th>
        </tr>
    </thead>
        <% @places.each_with_index do |place,index| %>
            <tbody>
            <td rowspan="1">
                <%= index %>
            </td>
            <td rowspan="1">
                <%= place.name %>
            </td>
            <td rowspan="1">
                <%= place.street %>
            </td>
            <td rowspan="1">
                <%= place.address %>
            </td>
            <td rowspan="1">
                <%= place.city %>
            </td>
            <td rowspan="1">
                <%= place.telephone_number %>
            </td>
            <td rowspan="1">
                <%= if(!place.opening_time.nil?); place.opening_time.strftime("%H:%M"); else  "-"; end; %>
            </td>
            <td rowspan="1">
                <%= if(!place.closing_time.nil?); place.closing_time.strftime("%H:%M"); else  "-"; end; %>
            </td>
            <td rowspan="1">
                <%= place.description %>
            </td>
            <td rowspan="1">
                <%= place.notices %>
            </td>
            <td rowspan="1">
                <% for i in 0..(place.average-1) do %>
                    <span style="font-size:200%;color:#efe801;">&starf;</span>
                <% end %>
            </td>
            <td rowspan="1">
                <%= link_to "#{place.name}", place_path(place) %>
            </td>
            <% end %>
            </tbody>
        </table>
    </font>
    <br/><br/><br/><br/>
<%end%>
    
    <div>
        <table style="width:60%">
          <thead>
          </thead>
          <tbody>
            <td><h2> Are you an Owner? Register your place </h2></td>
            <td><button type="button" class="btn btn-danger" style = "padding: 8px 40px;" onclick="window.location.href='/places/new'"><h5>Register Place</h5></button></td>          </tbody>
          </table>
    </div>

Travel/app/views/places/find_route.html.erb
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../../assets/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="../../assets/stylesheets/places/find_route.css" rel="stylesheet">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
</head>

<div id="logreg-forms">

    <h1 style="text-align:center" class="title"><strong>Find Route</strong></h1>
    <br/>
    <div class="field">
        <%= form_tag display_route_path, method: :get do %>
            <%= text_field_tag :From, "", class:"form-control", placeholder:"From"%><br/><br/>
        <div class="form">
            <div>
                <%= radio_button_tag :Facilities, "Car", id="radio1", :type=>"radio"%>
                <%= label_tag :Car %>
            </div>
            <div>
                <%= radio_button_tag :Facilities, "Public Transport", id="radio2", :type=>"radio"%>
                <%= label_tag 'Public Transport' %>
            </div>
        </div>
        <br/>

        <div style="max-width: 500px; margin: 20px auto;">

        <div class="container">
            <%= submit_tag "Find", name: nil, :class=>"btn btn-primary btn-block" %>
        </div>

        <% end %>
    </div>

</div>

Travel/app/views/places/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-11 scroll">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col"><h1>All Places</h1></th>
          </tr>
        </thead>
      </table>

<font size="2" >
<table style="width:100%">
 <thead>
    <tr>
      <th>Index</th>
      <th>Name</th>
      <th>Street</th>
      <th>Address</th>
      <th>City</th>
      <th>Telephone Number</th>
      <th>Opening Time</th>
      <th>Closing Time</th>
      <th>Description</th>
      <th>Notices</th>
      <th>Average</th>
      <th>More About</th>
    </tr>
  </thead>
    <% @places.each_with_index do |place,index| %>
        <tbody>
          <td rowspan="1">
            <%= index %>
          </td>
          <td rowspan="1">
            <%= place.name %>
          </td>
          <td rowspan="1">
            <%= place.street %>
          </td>
          <td rowspan="1">
            <%= place.address %>
          </td>
          <td rowspan="1">
            <%= place.city %>
          </td>
          <td rowspan="1">
            <%= if(place.telephone_number != ''); place.telephone_number; else "Unreported"; end; %>
          </td>
          <td rowspan="1">
            <%= if(!place.opening_time.nil?); place.opening_time.strftime("%H:%M"); else  "Unreported"; end; %>
          </td>
          <td rowspan="1">
            <%= if(!place.closing_time.nil?); place.closing_time.strftime("%H:%M"); else  "Unreported"; end; %>
          </td>
          <td rowspan="1">
            <%= if(place.description != ''); place.description; else "Unreported"; end; %>
          </td>
          <td rowspan="1">
            <%= if(place.notices != ''); place.notices; else "Unreported"; end; %>
          </td>
          <td rowspan='1'>
            <% for i in 0..(place.average.round-1) do %>
              <span style="font-size:200%;color:#efe801;">&starf;</span>
            <% end %>
          </td>
          <td rowspan="1">
            <%= link_to "#{place.name}", place_path(place) %>
          </td>
        <% end %>
        </tbody>
    </table>
</font>
<br/>

<button type="button" class="btn btn-danger" onclick="window.location.href='/places/new'"><a></a><h5>Add new Place</h5></button>

Travel/app/views/places/new.html.haml
= form_tag '/places', :method => :post do
    = render :partial => 'place_form'
    = submit_tag 'Save Changes'
    = link_to 'Cancel', places_path
%div
%div

Travel/app/views/places/show.html.erb
	<head>
	
		<link href="../../assets/stylesheets/place_info.css" rel="stylesheet">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400" rel="stylesheet">
		<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
		<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
		<link rel="stylesheet" type="text/css" href="../fonts/font-awesome-4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" type="text/css" href="../../vendor/animate/animate.css">
		<link rel="stylesheet" type="text/css" href="../../vendor/select2/select2.css">
		<link rel="stylesheet" type="text/css" href="../../vendor/perfect-scrollbar/perfect-scrollbar.css">
		<link rel="stylesheet" type="text/css" href="../../assets/stylesheets/util.css">
		<link rel="stylesheet" type="text/css" href="../../assets/stylesheets/main.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	
	</head>

<div>
  <% if current_user == @place.user %>
    <button type="button" id="Prova" class="btn btn-danger" onclick="window.location.href='/places/<%= @place.id %>/edit'">Modify</button>
  <% end %>
</div>

<div class="box">
    <h1 style="text-align:center">Details about <%= @place.name %> </h2> <br/>
    <div class="divsx">
      <ul>
        <li>Street:
          <%= @place.street  %>
        </li>
        <li>
          Address:
          <%= @place.address %>
        </li>
        <li>
          City:
          <%= @place.city %>
        </li>
        <li>
          Telephone Number:
          <% if @place.telephone_number != '' %>
            <%= @place.telephone_number %>
          <% else %>
            No telephone number for this place
          <% end %>
        </li>
        <li>
          Opening Time:
          <% if !@place.opening_time.nil? %>
            <%= @place.opening_time.strftime("%H:%M") %>
          <% else %>
            No opening time for this place
        <% end %>
        </li>
        <li>
          Closing Time:
          <% if !@place.closing_time.nil? %>
            <%= @place.closing_time.strftime("%H:%M") %>
          <% else %>
            No closing time for this place
          <% end %>
        </li>
        <li>
          Average Rating:
          <%= @place.average.round %>
        </li>
      </ul>
    
    <h3>Description:</h3>
    <p id="description">
    <% if !@place.description.nil? %>
      <%= @place.description %>
    <% else %>
      No description for this place
    <% end %>
    </p>
    <h3>Notices:</h3>
    <p id="notices">
    <% if !@place.notices.nil? %>
      <%= @place.notices %>
    <% else %>
      No notices for this place
    <% end %>
    </p>
    <h3>Owner Profile:</h3>
    <% if !@place.user.nil? %>
      <p id="owner">
      <p><button type="button" class="btn btn-danger" style = "padding: 6px 10px;" onclick="window.location.href='/users/<%= current_user.id %>'"><a></a><h5>Owner Profile</h5></button></p>
      </p>
    <% else %>
      <p></p>
      No owner for this place...
    <% end %>
      <h4>
      <%= link_to 'Back to Home Page', root_path %>
      <%= link_to 'Set as a favorite', set_favorite_path(:id => current_user.id, :place_id => @place.id) %>
      <% if ( current_user.is?(:moderator) || current_user.is?(:admin) || current_user == @place.user) %>
        <%= link_to 'Delete', place_path(@place), :method => :delete, :data => {confirm: 'Are you sure?'}; %>
      <% end %>
      <% if current_user == @place.user %>
        <%= link_to 'Edit', edit_place_path(@place) %>
      <% end %>
      <br/>
      <%= link_to 'Add review', new_place_review_path(@place) %>
    </h4>
</div>




<div class="divdx box">
<%= icon_for @place %>
<h3>Reviews:</h3>
<% if @place.reviews.empty? %>
  <p></p>
  No reviews for this place...
<% else %>
    <% if can? :read, Review %>
    <% reviews = @place.reviews.sort_by { |r| r.dislikes.count - r.likes.count } %>
    <%  reviews.each do |r| %>
      <% u = User.find_by_id(r.user_id) %>
      <% likes = r.likes.count %>
      <% dislikes = r.dislikes.count %>
      <% pre_like = r.likes.find { |like| like.user_id == current_user.id} %>
      <% pre_dislike = r.dislikes.find { |dislike| dislike.user_id == current_user.id} %>
      <h4><b> <%= r.rating %> </b> (<i><%= u.email %></i> - <i><%= link_to 'View profile', user_path(u) %></i>) <%= r.comments %> - <%= likes %> <%= (r.likes.count) == 1 ? 'Like' : 'Likes' %>
      <% if pre_like %>
        <%= link_to "Unlike", place_review_like_path(@place, r, pre_like), :method => :delete %>
      <% else %>
        <%= link_to 'Like', place_review_likes_path(@place, r), :method => :post %>
      <% end %> <%= dislikes %> <%= (r.dislikes.count) == 1 ? 'Dislike' : 'Dislikes' %>
      <% if pre_dislike %>
        <%= link_to "Undislike", place_review_dislike_path(@place, r, pre_dislike), :method => :delete %>
      <% else %>
        <%= link_to 'Dislike', place_review_dislikes_path(@place, r), :method => :post %>
      <% end %>
      <% if(u.email==current_user.email || current_user.is?(:admin) || current_user.is?(:moderator)) %>
        <%= link_to "Delete review", place_review_path(:id => r.id, :place_id => @place.id), :method => :delete, :data => {confirm: 'Are you sure?'} %>
      <% end %>
      <% if u.email==current_user.email %>
        <%= link_to "Edit review", edit_place_review_path(:id => r.id, :place_id => @place.id) %>
      <% end %> <br/>
    <% end %>
  <% else %>
    <b>You don't have the rights to read reviews.</b>
  <% end %>
</h4>
<br/><br/><br/><br/><br/><br/><br/>
<% end %>
<br/>
<button type="button" class="btn btn-danger" style = "padding: 8px 40px;" onclick="window.location.href='/places/<%= @place.id %>/find_route'"><h5>Find Route</h5></button>
</div>