Travel/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :reviews do
      resources :likes
      resources :dislikes
    end
  end
  
  resources :users

  get '/places/:place_id/set_favorite/:id', to: 'users#favorite', as: 'set_favorite'
  
  get '/static_pages/home/find', to: 'places#find', as: 'find_place'

  get '/places/my_reviews/:id', to: 'users#reviews', as: 'my_reviews'

  get '/users/:id/ban', to: 'users#ban', as: 'ban_user'

  get '/users/:id/unban', to: 'users#unban', as: 'unban_user'

  get '/users/:id/promote', to: 'users#promote', as: 'promote_user'
  
  get '/users/:id/demote', to: 'users#demote', as: 'demote_user'

  get '/places/:id/find_route', to: 'places#find_route',  as: 'find_route'

  get '/places/:id/display_route', to: 'places#display_route',  as: 'display_route'
  
  get 'static_pages/home'
  
  get 'static_pages/help'
  
  root :to  => redirect('/static_pages/home')

end

Travel/app/models/user.rb
class User < ApplicationRecord

  before_create :set_default_role
  before_create :set_num_likes_dislikes
  has_many :reviews
  has_many :places, :through => :reviews
  belongs_to :favorite_place  , optional: true, class_name: 'Place'
  has_many :likes, dependent: :destroy
  has_many :dislikes, dependent: :destroy
  has_many :property, class_name: 'Place'

  ROLES = [:admin, :moderator, :user, :owner, :banned]
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      parse_name(user, auth.info.name)
    end
    
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def roles= (roles)
    self.roles_mask = (roles & ROLES).map { |r| 2** ROLES.index(r) }.sum
  end
  
  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2** ROLES.index(r)).zero? }
  end
  
  def role_strings
    roles.map(& :to_s )
  end
  
  def is?(role)
    roles.include?(role)
  end
  
  private
  
  def set_default_role
    self.roles = [:user]
  end
  
  def self.parse_name(user, name)
    name_arr = name.split(" ")
    user.surname = name_arr.pop
    user.name = name_arr.join(" ")
  end

  def set_num_likes_dislikes
    self.num_likes = 0
    self.num_dislikes = 0
  end
  
  

end

Travel/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    
    def facebook
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
            set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
        else
            session["devise.facebook_data"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
    end
    
    def failure
        redirect_to root_path
    end

end

Travel/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!
    
    def index
        if current_user.is? :admin
            @users = User.all
        else
            flash[:warning] = "You cannot have access to the list of all users"
            redirect_to root_path
        end
    end
    
    def show
        begin
            id = params[:id] #retrieve user ID from URI route
            @user = User.find(id) # look up id bi unique ID
            authorize! :read, @user, :message => "BEWARE: You are not authorized to read an user."
        rescue ActiveRecord::RecordNotFound
            redirect_to root_path
            flash[:warning] = "There is no user with that index"
            return
        end
    end
    
    def new
        # default: render ’new’ template
    end

    def create
        @user = User.create!(user_params_create)
        if @user.save
            log_in @user
            flash[:success] = "Welcome on board!"
            redirect_to @user
        else
            render 'new'
        end
    end

    def edit
        @user = User.find params[:id]
        authorize! :update, @user, :message => "BEWARE: You are not authorized to edit an user."
        if current_user != @user
            flash[:warning] = "You are not authorized to edit this user"
            redirect_to user_path(@user)
        end
    end

    def update
        @user = User.find params[:id]
        authorize! :update, @user, :message => "BEWARE: You are not authorized to update an user."
        if current_user != @user
            flash[:warning] = "You are not authorized to update this user"
            redirect_to user_path(@user)
        end
        @user.update_attributes!()
        respond_to do |client_wants|
            client_wants.html {
                flash[:notice] = "#{@user.name} was successfully updated."
                redirect_to user_path(@user)
            }
            client_wants.xml { render :xml => @user.to_xml }
        end
    end

    def destroy
        @user = User.find(params[:id])
        if (@user.id == current_user.id || (current_user.is?(:admin) && !@user.is?(:admin)))
            @user.destroy
            flash[:notice] = "User #{@user.name} deleted."
        elsif (current_user.is?(:admin) && @user.is?(:admin))
            flash[:warning] = "You cannot delete another admin's profile"
        else
            flash[:warning] = "You cannot delete another user's profile"
        end
        redirect_to places_path
    end

    def favorite
        @user = User.find(params[:id])
        authorize! :update, @user, :message => "BEWARE: You are not authorized to update an user."
        @place = Place.find(params[:place_id])
        @user.favorite_place = @place
        @user.save!
        flash[:notice] = "Place #{@place.name} has been set as your favorite"
        redirect_to place_path(@place)
    end

    def reviews
        @user = User.find(params[:id])
        @reviews = @user.reviews
        # authorize! :read, @reviews, :message => "BEWARE: You are not authorized to read a review."
        # default: render ’reviews’ template
    end

    def ban
        if current_user.is? :admin
            @user = User.find(params[:id])
            @user.roles = @user.roles << :banned
            @user.save!
            flash[:notices] = "The user #{@user.name} has been successfully banned"
        else
            flash[:warning] = "You cannot ban another user"
        end
        redirect_to user_path(@user)
    end

    def unban
        if current_user.is? :admin
            @user = User.find(params[:id])
            @user.roles = @user.roles.reject{ |k| k==:banned}
            @user.save!
            flash[:notices] = "The user #{@user.name} has been successfully unbanned"
        else
            flash[:warning] = "You cannot unban another user"
        end
        redirect_to user_path(@user)
    end

    def promote
        if current_user.is? :admin
            @user = User.find(params[:id])
            if params[:role] == "Moderator"
                @user.roles = @user.roles << :moderator
                @user.save!
                flash[:notices] = "The user #{@user.name} has benn successfully promoted as moderator"
            else
                if !@user.is? :moderator
                    @user.roles = @user.roles << :moderator
                end
                @user.roles = @user.roles << :admin
                @user.save!
                flash[:notices] = "The user #{@user.name} has benn successfully promoted as admin"
            end
        else
            flash[:warning] = "You cannot promote another user"
        end
        redirect_to user_path(@user)
    end

    def demote
        if current_user.is? :admin
            @user = User.find(params[:id])
            if params[:role] == "Moderator"
                @user.roles = @user.roles.reject{ |k| k==:moderator}
                @user.save!
                flash[:notices] = "The user #{@user.name} has been successfully demoted from moderator"
            end
        else
            flash[:warning] = "You cannot demote another user"
        end
        redirect_to user_path(@user)
    end
    
    def user_params_create
        params[:user].permit(:name, :surname, :birth_date, :nickname, :email, :password, :password_confirmation, :bio)
    end
    
    def user_params_update
        params[:place].permit(:name, :surname, :birth_date, :nickname, :email, :password, :password_confirmation, :favorite_places, :bio)
    end

end

Travel/app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
      
    if user.avatar_url == nil || user.avatar_url == ""
        gravatar_url = "#{root_url}assets/pic.png"
      else
        gravatar_url = user.avatar_url
      end
      image_tag(gravatar_url, alt: user.avatar_url, class: "gravatar",  size: "180x180")
  end
  
end

Travel/app/views/users/edit.html.erb
<h2>Edit User</h2>
<%= form_tag user_path(@user), :method => :put do %>
  <%= label :user, :name, 'Name' %>
  <%= text_field :place, :name, required: true %>
  <%= label :user, :surname, 'Surname' %>
  <%= text_field :place, :name, required: true %>
  <%= label :user, :birth_date, 'Birth Date' %>
  <%= date_select :user, :birth_date, { start_year: 100.years.ago.year, end_year: Date.today.year, default: Date.today}, required: true %>
  <%= label :user, :nickname, "Nickname" %>
  <%= text_field :user, :nickname, required: true %>
  <%= label :user, :email, "Email" %>
  <%= text_field :user, :email, required: true %>
  <%= label :user, :bio, "Description" %>
  <%= text_area :user, :bio, cols: 30, rows: 10 %>
  <%= submit_tag 'Save Changes' %>
  <%= link_to 'Cancel', users_path %>
<% end %>

Travel/app/views/users/index.html.erb
<% if current_user.is? :admin %>
    <div class="container">
    <div class="row">
        <div class="col-md-11 scroll">
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th scope="col"><h1>All Users</h1></th>
            </tr>
            </thead>
        </table>

    <font size="3" >
    <table style="width:100%">
    <thead>
        <tr>
        <th>Index</th>
        <th>Name</th>
        <th>Surname</th>
        <th>Birth Date</th>
        <th>Nickname</th>
        <th>Email</th>
        <th>Favorite Place</th>
        <th>Bio</th>
        <th>Likes</th>
        <th>Dislikes</th>
        <th>Roles</th>
        <th>More</th>
        </tr>

    </thead>
        <% @users.each_with_index do |user,index| %>
        <tbody>
            <td rowspan="1">
            <%= index %>
            </td>
            <td rowspan="1">
            <%= user.name %>
            </td>
            <td rowspan="1">
            <%= user.surname %>
            </td>
            <td rowspan="1">
            <%= user.birth_date %>
            </td>
            <td rowspan="1">
            <%= user.nickname %>
            </td>
            <td rowspan="1">
            <%= user.email %>
            </td>
            <td rowspan="1">
            <%= user.favorite_place %>
            </td>
            <td rowspan="1">
            <%= user.bio %>
            </td>
            <td rowspan="1">
            <%= user.num_likes %>
            </td>
            <td rowspan="1">
            <%= user.num_dislikes %>
            </td>
            <td rowspan="1">
            <%= user.role_strings.join(',') %>
            </td>
            <td rowspan="1">
            <%= link_to "#{user.name}", user_path(user) %>
            </td>
        <% end %>
        </tbody>
    </table>
    </font>
<%else%>
    <h1>You don't have the rights to access this page!</h1>
<%end%>

Travel/app/views/users/new.html.erb
<h2>Register a new User</h2>
<%= form_tag users_path, :method => :post do %>
  <%= label :user, :name, 'Name' %>
  <%= text_field :user, :name, required: true %>
  <%= label :user, :surname, 'Surname' %>
  <%= text_field :user, :surname, required: true %>
  <%= label :user, :birth_date, 'Birth Date' %>
  <%= date_select :user, :birth_date, { start_year: 100.years.ago.year, end_year: Date.today.year, default: Date.today}, required: true %>
  <%= label :user, :nickname, "Nickname" %>
  <%= text_field :user, :nickname, required: true %>
  <%= label :user, :email, "Email" %>
  <%= text_field :user, :email, required: true %>
  <%= label :user, :bio, "Description" %>
  <%= text_area :user, :bio, cols: 30, rows: 10 %>
  <%= submit_tag 'Save Changes' %>
  <%= link_to 'Cancel', users_path %>
<% end %>

Travel/app/views/users/reviews.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 scroll">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th><h2>Reviews of <%= @user.name %> </h2></th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>


<% if can? :read, Review %>
  <% if @reviews.any? %>
    <font size="3" >
    <table style="width:100%">
    <% @reviews.each do |r| %>
    <tbody>
          <td rowspan="1"><% likes = r.likes.count %></td>
          <td rowspan="1"><% dislikes = r.dislikes.count %></td>
          <td rowspan="1"><% pre_like = r.likes.find { |like| like.user_id == @user.id} %></td>
          <td rowspan="1"><% pre_dislike = r.dislikes.find { |dislike| dislike.user_id == @user.id} %></td>
          <td rowspan="1"><b> <%= r.rating %> </b> (<i><%= @user.email %></i>) <%= r.comments %> </td>
          <td rowspan="1"><%= likes %> <%= (r.likes.count) == 1 ? 'Like' : 'Likes' %></td>
          <% if pre_like %>
              <td rowspan="1"><%= link_to "Unlike", place_review_like_path(r.place, r, pre_like), :method => :delete %></td>
          <% else %>
              <td rowspan="1"><%= link_to 'Like', place_review_likes_path(r.place, r), :method => :post %></td>
          <% end %> 
          <td rowspan="1"><%= dislikes %> <%= (r.dislikes.count) == 1 ? 'Dislike' : 'Dislikes' %></td>
          <% if pre_dislike %>
              <td rowspan="1"><%= link_to "Undislike", place_review_dislike_path(r.place, r, pre_dislike), :method => :delete %></td>
          <% else %>
              <td rowspan="1"><%= link_to 'Dislike', place_review_dislikes_path(r.place, r), :method => :post %></td>
          <% end %>
        
          <td rowspan="1"><%= link_to "Delete review", place_review_path(:id => r.id, :place_id => r.place.id), :method => :delete, :data => {confirm: 'Are you sure?'} %></td>
          <td rowspan="1"><%= link_to "Edit review", edit_place_review_path(:id => r.id, :place_id => r.place.id) %></td>
          <td rowspan="1"><%= link_to 'Back to Home Page', root_path %></td>
          <td rowspan="1"><%= "To the place: " %> <%= link_to "#{r.place.name}", place_path(r.place) %></td>
        </tbody>
    <%end%>
   </table>
    </font>
  <%else%>
    <h2>There aren't reviews associated with that user</h2>
  <%end%>
<% else %>
    <b>You don't have the centers to read reviews.</b>
<% end %>
    </div>
  </div>
</div>

Travel/app/views/users/show.html.erb
<head>
	
  <link href="../../assets/stylesheets/user/user.css" rel="stylesheet">
  
</head>



<h1 style="text-align:center"><strong>User Profile</strong></h1>

<div class="divsx col-md-5 boxphoto">
  <table style="width:90%">
  <tr>
    <th><%= gravatar_for @user %></th>
    <th><h1><%= @user.nickname %></h1></th>
  </tr>
  </table> 
  <br/>
</div>

<div class="divdx"></div>

  <div class="col-md-6 box">
    <div class="box">
      <h3>
        <strong>Name:</strong>
        <%= @user.name %>
        <br/>
        <strong>Surname:</strong>
        <%= @user.surname %>
        <br/>
        <strong>Birth Date:</strong>
        <%= @user.birth_date %>
        <br/>
        <strong>Email:</strong>
        <%= @user.email %>
        <br/>
      </h3>
      <h2><strong>Favorite Place:</strong></h2>
        <h3><% if(!@user.favorite_place.nil?) %>
          <%= link_to "#{@user.favorite_place.name}", place_path(@user.favorite_place) %>
        <% else  %>
          <p></p>
          This user does not have a favorite place
        <% end %></h3>
        
      <h2><strong>Satisfaction Index:</strong></h2>
        <h3><% if @user.num_dislikes == 0 %>
          <p></p>
          This user has no dislikes
        <% else %>
          <%= @user.num_likes / @user.num_dislikes %>
        <% end %>
        </h3>
        
      <h2><strong>Bio:</strong></h2>
      <h3><p id="bio">
      <%= @user.bio %>
      </p>
      </h3>

      <h2> <strong>Roles:</strong> </h2>
      <h3> <%= @user.role_strings.join(', ') %> </h3>

      <% if(current_user.is?(:admin) && !@user.is?(:banned) &&  !@user.is?(:admin))%>
        
        <h2> <strong> Promote as: </strong> </h2>
        <%= form_tag promote_user_path(@user), method: :get do %>
          <% if !@user.is? :moderator %>
            <%= label_tag :moderator %>
            <%= radio_button_tag :role, "Moderator" %>
          <% end %>
          <%= label_tag :admin %>
          <%= radio_button_tag :role, "Admin" %>
          <%= submit_tag "Promote", name: nil %>
        <% end %>

        <% if @user.is? :moderator %>
          <h2> <strong> Demote as: </strong> </h2>
          <%= form_tag demote_user_path(@user), method: :get do %>
            <%= label_tag :moderator %>
            <%= radio_button_tag :role, "Moderator" %>
            <%= submit_tag "Demote", name: nil %>
          <% end %>
        <% end %>


      <% end %>
      
      </div>

</div>

<table style="width:50%">
  <tr>
    <th><% if current_user == @user %>
      <h5><p><button type="button" class="btn btn-danger" style = "padding: 8px 40px;" onclick="window.location.href='/users/edit'">Edit Info</button></p></h5>
    <%end%>
    </th>

    <th>
      <p><button type="button" class="btn btn-danger" style = "padding: 8px 30px;" onclick="window.location.href='/static_pages/home'"><a></a><h5>Back to Home Page</h5></button></p>
    </th>
    
    <th><% if(current_user == @user || (current_user.is?(:admin) && !@user.is?(:admin))) %>
      <p><button type="button" class="btn btn-danger btn-primary" style="padding: 8px 30px">
        <strong><%= link_to 'Delete', user_path(@user), :method => :delete, :data => {confirm: 'Are you sure?'}, style: "color: white" %></strong>
      </button></p>
    <%end %>
    </th>

    <th> <% if (current_user.is?(:admin) && !@user.is?(:admin)) %>
      <% if !@user.is? :banned %>
        <%= link_to 'Ban', ban_user_path(@user) %>
      <% else %>
        <%= link_to 'Unban', unban_user_path(@user) %>
      <% end %>
    <% end %>
    </th>
  
  </tr>
</table>