Travel/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :reviews do
      resources :likes
      resources :dislikes
    end
  end
  
  resources :users

  get '/places/:place_id/set_favorite/:id', to: 'users#favorite', as: 'set_favorite'
  
  get '/static_pages/home/find', to: 'places#find', as: 'find_place'

  get '/places/my_reviews/:id', to: 'users#reviews', as: 'my_reviews'

  get '/users/:id/ban', to: 'users#ban', as: 'ban_user'

  get '/users/:id/unban', to: 'users#unban', as: 'unban_user'

  get '/users/:id/promote', to: 'users#promote', as: 'promote_user'
  
  get '/users/:id/demote', to: 'users#demote', as: 'demote_user'

  get '/places/:id/find_route', to: 'places#find_route',  as: 'find_route'

  get '/places/:id/display_route', to: 'places#display_route',  as: 'display_route'
  
  get 'static_pages/home'
  
  get 'static_pages/help'
  
  root :to  => redirect('/static_pages/home')

end

Travel/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :authenticate_user!

    def new
        # default: render ’new’ template
    end

    def create
        id_place = params[:place_id]
		@place = Place.find(id_place)
        @user = current_user
        pre_average = @place.average
        @review = @place.reviews.build(params[:review].permit(:rating, :comments))
        authorize! :create, @review, :message => "BEWARE: You are not authorized to create a new review."
        @user.reviews << @review
        @review.save!
        @place.average = ((pre_average * (@place.reviews.count - 1)) + @review.rating) / @place.reviews.count
        @place.save!
        respond_to do |client_wants|
            client_wants.html {
                flash[:notice] = "A review has from #{@user.email} been successfully added to #{@place.name}."
                redirect_to place_path(@place)
            }
            client_wants.xml { render :xml => @review.to_xml }
        end
    end

    
    def edit
        @review = Review.find params[:id]
        authorize! :update, @review, :message => "BEWARE: You are not authorized to edit a review."
        flash[:previous_page] = request.referer
    end

    def update
        @review = Review.find params[:id]
        authorize! :update, @review, :message => "BEWARE: You are not authorized to update a review."
        @place = @review.place
        @place.average = @place.average * @place.reviews.count - @review.rating
        @review.update_attributes!(params[:review].permit(:rating, :comments))
        @place.average = (@place.average + @review.rating) / @place.reviews.count
        @place.save!
        respond_to do |client_wants|
            client_wants.html {
                flash[:notice] = "Review was successfully added."
                redirect_to flash[:previous_page]
            }
            client_wants.xml { render :xml => @review.to_xml }
        end
    end

    def destroy
        id = params[:id]
        @review = Review.find(id)
        if(current_user == @review.user || current_user.is?(:moderator) || current_user.is?(:admin))
            id_place = params[:place_id]
            @place = Place.find(id_place)
            authorize! :destroy, @review, :message => "BEWARE: You are not authorized to delete a review."
            if @place.reviews.count == 1
                @place.average = 0
            else
                @place.average = (@place.average * @place.reviews.count - @review.rating) / (@place.reviews.count - 1)
            end
            @place.save!
            @review.destroy
            flash[:notice] = "The review of #{@review.user.email} has been deleted."
        else
            flash[:warning] = "You cannot delete the review of another user"
        end
        redirect_to request.referer
    end

end

Travel/app/views/reviews/_review_form.html.haml
%div
  .col-md-5.box
    %div
      .field

        = label :review, :rating, 'Votes'
        = select :review, :rating, [1,2,3,4,5], required: true
        %br/
        %br/
        = label :review, :comments, 'Comment'
        = text_field :review, :comments, required: true , :id => 'com'
 
  

Travel/app/views/reviews/edit.html.haml
%h2 Edit Review
 
= form_tag place_review_path(@review), :method => :put do
    = render :partial => 'review_form'
    = submit_tag 'Update Review'

= link_to 'Cancel', request.referer

Travel/app/views/reviews/index.html.haml
%h1 All Reviews
 
%table#reviews
  %thead
    %tr
      %th Index
      %th Place
      %th User
      %th Description
  %tbody
    - @reviews.each_with_index do |review,index|
      %tr.row
        %td= index
        %td= review.place
        %td= review.user
        %td= review.description
        %td= link_to "More about #{review.name}", review_path(review)

= link_to 'Add new review', new_review_path

Travel/app/views/reviews/new.html.haml
%h2 Add a comment
 
= form_tag place_reviews_path, :method => :post do
 
  = render :partial => 'review_form'
  = submit_tag 'Save Changes', :id => 'sav'

= link_to 'Cancel', place_path(:id => params[:place_id])

  



  

  

  

Travel/app/views/reviews/show.html.haml
%h2 Details about #{@review.place}
 
%ul#details
  %li
    Place:
    = @review.place
  %li
    User:
    = @review.user

%h3 Description:
 
%p#description= @review.description

= link_to 'Edit info', edit_review_path(@review)
= link_to 'Delete', review_path(@review), :method => :delete, :data => {confirm: 'Are you sure?'}
= link_to 'Back to review list', review_path